<!--<table class="colbackstyle" width=>
<tr>
       <td><a class="menu" href="#" alt="Login">Login</a></td> <td class="colbackstyle2"> 
	</td><td><a class="menu" href="default.php?pid=setup" alt="Setup">Setup lookup tables</a></td>
	<td class="colbackstyle2"></td><td><a class="menu" href="default.php?pid=vw_projects" alt="Project Information">Project Info</a></td>
	<td class="colbackstyle2"></td><td><a class="menu" href="#" alt="Reporting Facilities">Reports</a></td>
	<td class="colbackstyle2"></td><td><a class="menu" href="default.php?pid=logout" alt="logout">Logout</a></td>
	<td class="colbackstyle2"></td><td><a class="menu" href="default.php?pid=vw_main" alt=\All Testcase Listing\">Run Test Case</a></td>

</tr></table>-->

<table class="colbackstyle" width=350>
<tr>
       <!--<td><a class="menu" href="#" alt="Login">Login</a></td> <td class="colbackstyle2"> -->
	</td><td><a class="menu" href="default.php?pid=selmain" alt="Home">Home</a></td>
	<td class="colbackstyle2"></td><td><a class="menu" href="#" alt="Project Team">Project Team</a></td>
	<td class="colbackstyle2"></td><td><a class="menu" href="#" alt="Documentation">Documentation</a></td>
	  <td class="colbackstyle2"></td><td><a class="menu" href="#" alt="Contact Us">Contact Us</a></td>
	<!--<td class="colbackstyle2"></td><td><a class="menu" href="default.php?pid=vw_main" alt=\All Testcase Listing\">Run Test Case</a></td>-->

</tr></table>